spring:
  application:
    name: philippines
  data:
    mongodb:
      host: ${mongo.host}
      port: ${mongo.port}
      database: ${mongo.database}
      username: ${mongo.username}
      password: ${mongo.password}
      authentication-database: admin